variable vpc_id {}
variable admin_access_cidr_blocks {}
variable aws_ami_id {}
variable instance_type {}
variable instance_count {}
variable available_zone {}
variable subnet_id {}
variable prefix {}
variable ssh_key_name {}
variable ssh_key_path {}
variable srcs {}