---
- name: Check the server is ready
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure SSH port is open
      wait_for:
        port: 22
        delay: 10
        timeout: 180
        search_regex: OpenSSH
        host: "{{ ansible_ssh_host | default(ansible_host) | default(inventory_hostname) }}"
      vars:
        ansible_connection: local

- name: Install Docker and Docker Compose
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - ca-certificates
          - curl
          - apt-transport-https
          - software-properties-common
        update_cache: yes
        state: present
    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository to apt sources
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu noble stable
        state: present
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        update_cache: yes
        state: present

- name: Start Docker
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Add ansible_user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: Restart SSH session after Docker group update
      meta: reset_connection
    - name: Start Docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Prepare environment
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Copy Docker Compose environment
      copy:
        src: "{{ srcs }}"
        dest: "/home/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    - name: Create directory for SSL certificates
      file:
        path: "/home/{{ ansible_user }}/srcs/nginx/certs"
        state: directory
        mode: '0755'
    - name: Generate private key for SSL
      openssl_privatekey:
        path: "/home/{{ ansible_user }}/srcs/nginx/certs/server.key"
    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "/home/{{ ansible_user }}/srcs/nginx/certs/server.crt"
        privatekey_path: "/home/{{ ansible_user }}/srcs/nginx/certs/server.key"
        provider: selfsigned

- name: Run application
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Start Docker containers
      community.docker.docker_compose_v2:
        project_src: "/home/{{ ansible_user }}/srcs/"
        state: present